<?php
/**
 * @author Hgati Team
 * @copyright Copyright (c) 2021 Hgati
 * @package Hgati_Webp
 */

use Hgati\Webp\Block\Adminhtml\Conversion\Tree;

/** @var Tree $block */
?>

<div class="webp-folders-side-col">
    <div class="tree-holder">
        <div id="folder-tree"></div>
    </div>
</div>

<script>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();?>
<?php $areaList = $objectManager->get("\Magento\Framework\App\AreaList");?>
<?php $adminPath = $areaList->getFrontName('adminhtml');?>
const treeNodeAdminPath = "<?php echo $adminPath;?>";
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "Hgati_Webp/js/conversion/treenode": {}
        }
    }
</script>
